export type FinancialDiscoveryInput={monthlyIncome:number;monthlyExpenses:number;liquidAssets:number;totalAssets:number;totalLiabilities:number;protectedAmount?:number|null;incomeReplacementMonths?:number;businessValue?:number|null;businessOwnershipPct?:number|null};
const round=(n:number)=>Math.round(n*100)/100; const safe=(n:number)=>Number.isFinite(n)?Math.max(0,n):0;
export function analyzeFinancialProtection(i:FinancialDiscoveryInput){
 const income=safe(i.monthlyIncome),expenses=safe(i.monthlyExpenses),liquid=safe(i.liquidAssets),assets=safe(i.totalAssets),liabilities=safe(i.totalLiabilities),protectedAmount=safe(i.protectedAmount??0);
 const cashFlow=income-expenses; const liquidityMonths=expenses>0?round(liquid/expenses):null; const debtRatio=assets>0?round(liabilities/assets*100):null; const savingsRate=income>0?round(Math.max(0,cashFlow)/income*100):null;
 const replacementMonths=Math.max(3,Math.round(i.incomeReplacementMonths??12)); const replacementNeed=expenses*replacementMonths; const protectionGap=Math.max(0,replacementNeed-protectedAmount-liquid);
 const businessExposure=i.businessValue!=null&&i.businessOwnershipPct!=null?safe(i.businessValue)*Math.min(100,safe(i.businessOwnershipPct))/100:null;
 const healthParts=[liquidityMonths==null?null:Math.min(100,liquidityMonths/6*100),debtRatio==null?null:Math.max(0,100-debtRatio),savingsRate==null?null:Math.min(100,savingsRate*4)].filter((x):x is number=>x!=null);
 const healthIndex=healthParts.length?round(healthParts.reduce((a,b)=>a+b,0)/healthParts.length):null;
 const gaps=[...(protectionGap>0?[{category:"income_continuity",needAmount:replacementNeed,protectedAmount:protectedAmount+liquid,gapAmount:round(protectionGap),severity:protectionGap>replacementNeed*.6?"HIGH":"MEDIUM",evidence:`Liquid assets plus declared protection do not cover ${replacementMonths} months of expenses.`,confidence:90}]:[]),...(businessExposure!=null&&assets>0&&businessExposure/assets>.5?[{category:"business_concentration",needAmount:null,protectedAmount:null,gapAmount:null,severity:"HIGH",evidence:`Estimated business exposure represents ${round(businessExposure/assets*100)}% of declared assets.`,confidence:75}]:[])];
 return {health:{index:healthIndex,cashFlow:round(cashFlow),liquidityMonths,debtRatio,savingsRate},protection:{replacementMonths,replacementNeed:round(replacementNeed),gapAmount:round(protectionGap)},businessExposure:businessExposure==null?null:round(businessExposure),gaps,actionPlan:gaps.map((g,idx)=>({objective:g.category==="income_continuity"?"Increase contingency resilience":"Reduce concentration between personal wealth and business exposure",gap:g.evidence,alternatives:["Increase liquidity reserve","Review protection alternatives with an authorized professional","Reduce concentration through a documented financial plan"],expectedImpact:"Reduce the identified exposure while preserving client choice.",priority:idx+1})),disclaimer:"VELA supports analysis and planning. Regulated financial or insurance product recommendations remain the responsibility of the appropriately authorized professional."};
}
export function simulateFinancialShock(i:FinancialDiscoveryInput,shock:{incomeDropPct:number;months:number;extraMonthlyCost?:number}){
 const income=safe(i.monthlyIncome)*(1-Math.min(100,safe(shock.incomeDropPct))/100);const expense=safe(i.monthlyExpenses)+safe(shock.extraMonthlyCost??0);const monthlyDelta=income-expense;const endingLiquidity=round(safe(i.liquidAssets)+monthlyDelta*Math.max(1,Math.round(shock.months)));return {monthlyIncomeAfterShock:round(income),monthlyNetCashFlow:round(monthlyDelta),endingLiquidity,liquidityExhausted:endingLiquidity<0,months:Math.max(1,Math.round(shock.months))};
}
