import {analyzeFinancials,type FinancialInput} from "@/lib/valuation-engine";

export type RiskEvidence={customerConcentrationPct?:number|null;supplierConcentrationPct?:number|null;founderDependencyPct?:number|null;technologyDependencyPct?:number|null;complianceOpenItems?:number|null;cyberControlsCoveragePct?:number|null;territorialExposurePct?:number|null};
export type RiskSignalInput={dimension:string;signal:string;evidence:string;exposure:number;probability:number;impact:number;confidence:number;action?:string;targetMetric?:string;currentValue?:number;targetValue?:number};
const clamp=(n:number)=>Math.max(0,Math.min(100,n)); const round=(n:number)=>Math.round(n*100)/100;
export function scoreSignal(s:RiskSignalInput){return round(clamp(s.exposure)*clamp(s.probability)*clamp(s.impact)/10000);}
export function analyzeEnterpriseRisk(financial:FinancialInput,e:RiskEvidence={}){
 const f=analyzeFinancials(financial); const signals:RiskSignalInput[]=[];
 const add=(s:RiskSignalInput)=>signals.push({...s,exposure:clamp(s.exposure),probability:clamp(s.probability),impact:clamp(s.impact),confidence:clamp(s.confidence)});
 if(f.burn>0&&f.runwayMonths!=null&&f.runwayMonths<12)add({dimension:"financial",signal:"Liquidity runway exposure",evidence:`Current runway is ${f.runwayMonths} months with monthly burn ${f.burn}.`,exposure:clamp((12-f.runwayMonths)/12*100),probability:70,impact:85,confidence:95,action:"Create a cash preservation and financing plan.",targetMetric:"runwayMonths",currentValue:f.runwayMonths,targetValue:12});
 if((e.customerConcentrationPct??0)>=40)add({dimension:"commercial",signal:"Customer concentration",evidence:`${e.customerConcentrationPct}% of revenue is concentrated in the principal customer or customer group.`,exposure:e.customerConcentrationPct!,probability:65,impact:85,confidence:92,action:"Diversify commercial pipeline and reduce concentration.",targetMetric:"customerConcentrationPct",currentValue:e.customerConcentrationPct!,targetValue:40});
 if((e.supplierConcentrationPct??0)>=50)add({dimension:"operations",signal:"Critical supplier dependency",evidence:`${e.supplierConcentrationPct}% supplier dependency reported.`,exposure:e.supplierConcentrationPct!,probability:55,impact:75,confidence:85,action:"Qualify alternative suppliers and continuity procedures.",targetMetric:"supplierConcentrationPct",currentValue:e.supplierConcentrationPct!,targetValue:40});
 if((e.founderDependencyPct??0)>=50)add({dimension:"people",signal:"Founder dependency",evidence:`${e.founderDependencyPct}% of critical operation depends on the founder.`,exposure:e.founderDependencyPct!,probability:60,impact:90,confidence:88,action:"Document critical processes, delegate authority and establish continuity coverage.",targetMetric:"founderDependencyPct",currentValue:e.founderDependencyPct!,targetValue:35});
 if((e.cyberControlsCoveragePct??100)<70)add({dimension:"technology",signal:"Cyber control coverage gap",evidence:`Reported control coverage is ${e.cyberControlsCoveragePct}%.`,exposure:100-(e.cyberControlsCoveragePct??0),probability:55,impact:80,confidence:80,action:"Prioritize missing controls and recovery testing.",targetMetric:"cyberControlsCoveragePct",currentValue:e.cyberControlsCoveragePct??0,targetValue:85});
 if((e.complianceOpenItems??0)>0)add({dimension:"legal_compliance",signal:"Open compliance obligations",evidence:`${e.complianceOpenItems} open compliance item(s) reported.`,exposure:clamp((e.complianceOpenItems??0)*15),probability:55,impact:70,confidence:85,action:"Assign owners and closure dates to compliance obligations."});
 if((e.territorialExposurePct??0)>=50)add({dimension:"territorial_environmental",signal:"Territorial concentration exposure",evidence:`${e.territorialExposurePct}% of operations or assets are concentrated in the reported territory.`,exposure:e.territorialExposurePct!,probability:45,impact:70,confidence:70,action:"Assess location-specific hazards before declaring territorial risk.",targetMetric:"territorialExposurePct",currentValue:e.territorialExposurePct!,targetValue:40});
 const scored=signals.map(s=>({...s,riskScore:scoreSignal(s)})).sort((a,b)=>b.riskScore-a.riskScore);
 const avg=scored.length?scored.reduce((a,b)=>a+b.riskScore,0)/scored.length:0; const resilience=round(clamp(100-avg));
 const confidence=scored.length?round(scored.reduce((a,b)=>a+b.confidence,0)/scored.length):0;
 return {status:scored.length?"SIGNALS_DETECTED":"INSUFFICIENT_OR_LOW_RISK_EVIDENCE",resilienceIndex:resilience,confidence,signals:scored,components:{financial:{burn:f.burn,runwayMonths:f.runwayMonths},signalCount:scored.length},explanation:"Resilience is an evidence-linked operating indicator. It is not an insurance underwriting decision, credit rating, or guarantee."};
}
