"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
type R={id:string;title:string;desc:string;resourceType:string;status:string;criticality:string;monthlyCost:number|null;usageStatus:string;allocations:number};
export default function ResourcesWorkspace(){
 const [data,setData]=useState<any>(null);const [show,setShow]=useState(false);const [form,setForm]=useState({title:"",desc:"",resourceType:"tool",criticality:"normal",monthlyCost:""});
 async function load(){const r=await fetch("/api/resources",{cache:"no-store"});if(r.ok)setData(await r.json())}
 useEffect(()=>{void load();const e=new EventSource("/api/home/events");let t:any;const refresh=()=>{clearTimeout(t);t=setTimeout(()=>void load(),250)};e.addEventListener("domain-event",refresh);return()=>{clearTimeout(t);e.close()}},[]);
 async function create(){const r=await fetch("/api/resources",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,monthlyCost:form.monthlyCost?Number(form.monthlyCost):null})});if(r.ok){setShow(false);setForm({title:"",desc:"",resourceType:"tool",criticality:"normal",monthlyCost:""});await load()}}
 const intel=data?.intelligence;
 return <div className="resources-shell"><header className="resources-header"><div><span className="home-eyebrow">Resource system</span><h1>Resources</h1><p>Inventory, ownership, cost and allocation for the capabilities your venture actually depends on.</p></div><button className="btn-primary" onClick={()=>setShow(!show)}>+ Add resource</button></header>
 {show&&<section className="resources-form"><input className="os-input" placeholder="Resource name" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><textarea className="os-input os-textarea" placeholder="What is it used for?" value={form.desc} onChange={e=>setForm({...form,desc:e.target.value})}/><select className="os-input" value={form.resourceType} onChange={e=>setForm({...form,resourceType:e.target.value})}>{["tool","infrastructure","dataset","service","budget","knowledge","asset"].map(x=><option key={x}>{x}</option>)}</select><select className="os-input" value={form.criticality} onChange={e=>setForm({...form,criticality:e.target.value})}><option value="normal">normal</option><option value="critical">critical</option></select><input className="os-input" type="number" min="0" placeholder="Monthly cost" value={form.monthlyCost} onChange={e=>setForm({...form,monthlyCost:e.target.value})}/><button className="btn-primary" disabled={!form.title.trim()} onClick={create}>Create</button></section>}
 <section className={`resources-command resources-command-${(intel?.status??"SETUP").toLowerCase()}`}><div><span className="home-eyebrow">Resource Intelligence</span><small>{intel?.focus??"Resource setup"}</small></div><div><h2>{intel?.title??"Build the venture resource inventory."}</h2><p>{intel?.explanation}</p></div><strong>{intel?.confidence??"LOW"} confidence</strong></section>
 <section className="resources-strip"><Stat label="Resources" value={intel?.health.total??0}/><Stat label="Available" value={intel?.health.available??0}/><Stat label="Allocated" value={intel?.health.allocated??0}/><Stat label="Monthly cost" value={intel?.health.monthlyCost!=null?new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(intel.health.monthlyCost):"—"}/></section>
 <section className="resources-inventory"><div className="home-section-heading"><div><span className="home-eyebrow">Operating inventory</span><h2>Resource capacity</h2></div><Link href="/team">Team ownership →</Link></div>{data?.resources?.length?<div className="resources-grid">{data.resources.map((r:R)=><article className="resource-card" key={r.id}><div><span className="home-eyebrow">{r.resourceType}</span><h3>{r.title}</h3><p>{r.desc||"No operating description"}</p></div><div className="resource-meta"><span>{r.status}</span><span>{r.criticality}</span><span>{r.allocations} allocation(s)</span><span>{r.usageStatus}</span></div>{r.monthlyCost!=null&&<strong>{new Intl.NumberFormat("es-CO",{style:"currency",currency:"COP",maximumFractionDigits:0}).format(r.monthlyCost)}/mo</strong>}</article>)}</div>:<div className="resources-empty">No venture resources registered yet.</div>}</section></div>
}
function Stat({label,value}:{label:string;value:string|number}){return <div className="resources-stat"><span>{label}</span><strong>{value}</strong></div>}
