import {NextRequest,NextResponse} from "next/server";
import {requireAuth} from "@/lib/api-auth"; import {prisma} from "@/lib/prisma";
import {forecastFinancials,investorQuestions} from "@/lib/financial-forecasting";
import {valueVenture} from "@/lib/valuation-engine"; import {dispatchDomainEvent} from "@/lib/domain-events";
export const dynamic="force-dynamic";
async function ctx(ownerId:string){const venture=await prisma.venture.findUnique({where:{userId:ownerId}});if(!venture)return null;const [latest,scenarios,benchmarks,iot]=await Promise.all([prisma.financialSnapshot.findFirst({where:{ventureId:venture.id},orderBy:{period:"desc"}}),prisma.forecastScenario.findMany({where:{ventureId:venture.id},orderBy:{createdAt:"desc"},take:10}),prisma.financialBenchmark.findMany({where:{ventureId:venture.id},orderBy:{createdAt:"desc"},take:30}),prisma.ioTFinancialSignal.findMany({where:{ventureId:venture.id},orderBy:{observedAt:"desc"},take:50})]);return{venture,latest,scenarios,benchmarks,iot};}
export async function GET(req:NextRequest){const a=await requireAuth(req);if(!a.ok)return a.response;const c=await ctx(a.session.sub);if(!c)return NextResponse.json({status:"NO_VENTURE"});const last=await prisma.valuationCase.findFirst({where:{ventureId:c.venture.id},orderBy:{createdAt:"desc"}});return NextResponse.json({...c,investorRoom:investorQuestions(c.latest,last?.result,c.benchmarks.length,c.iot.length)});}
export async function POST(req:NextRequest){const a=await requireAuth(req);if(!a.ok)return a.response;const c=await ctx(a.session.sub);if(!c)return NextResponse.json({error:"Create a venture first."},{status:409});const b=await req.json().catch(()=>({}));const n=(v:unknown)=>Number(v);
 if(b.kind==="forecast"){if(!c.latest)return NextResponse.json({error:"Financial snapshot required."},{status:409});const assumptions={months:n(b.months)||12,revenueGrowth:n(b.revenueGrowth),costGrowth:n(b.costGrowth),volatility:n(b.volatility)||0,simulations:n(b.simulations)||1000,seed:n(b.seed)||872};if(!Number.isFinite(assumptions.revenueGrowth)||!Number.isFinite(assumptions.costGrowth))return NextResponse.json({error:"Growth assumptions required."},{status:400});const result=forecastFinancials(c.latest,assumptions);const row=await prisma.forecastScenario.create({data:{ventureId:c.venture.id,name:String(b.name||"Base forecast"),...assumptions,result:result as unknown as object}});await dispatchDomainEvent("financial_forecast_created",{forecastId:row.id,ventureId:c.venture.id,ownerId:a.session.sub});return NextResponse.json({...row,result},{status:201});}
 if(b.kind==="benchmark"){if(!b.metric||!b.sourceName||!b.unit||!Number.isFinite(n(b.value)))return NextResponse.json({error:"metric, value, unit and sourceName required."},{status:400});const row=await prisma.financialBenchmark.create({data:{ventureId:c.venture.id,metric:String(b.metric),value:n(b.value),unit:String(b.unit),cohort:b.cohort?String(b.cohort):null,sourceName:String(b.sourceName),sourceUrl:b.sourceUrl?String(b.sourceUrl):null,observedAt:b.observedAt?new Date(b.observedAt):null}});return NextResponse.json(row,{status:201});}
 if(b.kind==="iot"){if(!b.metric||!b.unit||!b.source||!Number.isFinite(n(b.value)))return NextResponse.json({error:"metric, value, unit and source required."},{status:400});const row=await prisma.ioTFinancialSignal.create({data:{ventureId:c.venture.id,metric:String(b.metric),value:n(b.value),unit:String(b.unit),financialMetric:b.financialMetric?String(b.financialMetric):null,conversionRate:b.conversionRate==null||b.conversionRate===""?null:n(b.conversionRate),source:String(b.source),observedAt:b.observedAt?new Date(b.observedAt):new Date()}});await dispatchDomainEvent("iot_financial_signal_recorded",{signalId:row.id,ventureId:c.venture.id,ownerId:a.session.sub,metric:row.metric});return NextResponse.json(row,{status:201});}
 return NextResponse.json({error:"Unsupported kind."},{status:400});
}