import {detectMultivariateAnomalies} from "../anomaly/multivariate";import {optimizeDiscrete} from "../optimization/aco";import {buildPortfolioMatrix,standardizeMatrix,type PortfolioVenture} from "./matrix";import {segmentPortfolio} from "./segmentation";
export const PORTFOLIO_INTELLIGENCE_VERSION="PORTFOLIO_INTELLIGENCE_V1";
export function analyzePortfolio(ventures:PortfolioVenture[],options?:{keys?:string[];clusters?:number;minimumFeatureCoverage?:number;interventionCapacity?:number;priority?:Record<string,number>;risk?:Record<string,number>}){
 const matrix=buildPortfolioMatrix(ventures,options?.keys,options?.minimumFeatureCoverage??.7);if(matrix.rows.length<2||!matrix.featureKeys.length)return{status:"INSUFFICIENT_DATA" as const,version:PORTFOLIO_INTELLIGENCE_VERSION,total:ventures.length,eligible:matrix.ventureIds.length,features:matrix.featureKeys,excluded:matrix.excluded};
 const normalized=standardizeMatrix(matrix.rows),seg=segmentPortfolio(normalized.rows,options?.clusters??Math.min(3,matrix.rows.length)),anomaly=matrix.rows.length>=3?detectMultivariateAnomalies(normalized.rows):null;
 const outliers=anomaly?.status==="AVAILABLE"?anomaly.anomalies.map(a=>({ventureId:matrix.ventureIds[a.index],distance:a.distance,severity:a.severity,evidence:a.evidence})):[];
 const clusters=seg.status==="AVAILABLE"?seg.clusters.map((members,id)=>({id,ventureIds:members.map(i=>matrix.ventureIds[i]),size:members.length})):[];
 const capacity=Math.max(0,Math.floor(options?.interventionCapacity??0));const allocation=capacity?optimizeDiscrete(matrix.ventureIds.map(id=>({id,utility:Math.max(0,options?.priority?.[id]??options?.risk?.[id]??0),cost:1,risk:0})),capacity,{seed:872}):null;
 const risks=matrix.ventureIds.map(id=>options?.risk?.[id]).filter((x):x is number=>typeof x==="number"&&Number.isFinite(x));
 return{status:"AVAILABLE" as const,version:PORTFOLIO_INTELLIGENCE_VERSION,summary:{total:ventures.length,eligible:matrix.ventureIds.length,excluded:matrix.excluded.length,featureCount:matrix.featureKeys.length,clusterCount:clusters.length,outlierCount:outliers.length,averageRisk:risks.length?Math.round(risks.reduce((a,b)=>a+b,0)/risks.length*100)/100:null},features:matrix.featureKeys,clusters,outliers,interventionAllocation:allocation?{selected:allocation.selected,score:allocation.score,capacity,feasible:allocation.feasible}:null,excluded:matrix.excluded,notes:["Clusters indicate statistical similarity, not business quality.","Outliers indicate statistical deviation, not automatically risk or misconduct.","Intervention allocation only uses supplied priority/risk values; it does not infer causal impact."]};
}
