"use client";import {FormEvent,useEffect,useState} from "react";
const initial={name:"Growth + funding",capitalRaise:"",equityOffered:"",revenueChangePct:"0",customerChangePct:"0",cacChangePct:"0",monthlyHiringCost:"0",additionalMonthlyCosts:"0",debtChange:"0",months:"12",revenueGrowth:"5",costGrowth:"3",volatility:"0.08",simulations:"1000",seed:"872",revenueMultiple:"",ebitdaMultiple:"",discountRate:"",terminalGrowth:"",projectedGrowth:""};
export default function CapitalDigitalTwin(){const[form,setForm]=useState<any>(initial),[result,setResult]=useState<any>(null),[history,setHistory]=useState<any[]>([]),[busy,setBusy]=useState(false);const load=async()=>{const r=await fetch("/api/capital/digital-twin",{cache:"no-store"});if(r.ok){const p=await r.json();setHistory(p.scenarios??[])}};useEffect(()=>{void load()},[]);
const run=async(e:FormEvent)=>{e.preventDefault();setBusy(true);const r=await fetch("/api/capital/digital-twin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const p=await r.json();if(r.ok){setResult(p);await load()}setBusy(false)};const fmt=(v:any)=>v==null?"—":new Intl.NumberFormat("es-CO",{maximumFractionDigits:0}).format(v);
return <section className="digital-twin"><div className="valuation-head"><div><span className="home-eyebrow">Capital Digital Twin</span><h2>Scenario Propagation Engine</h2><p>Change the hypothetical future without changing the venture's real operating data.</p></div><span className="badge badge-accent">TWIN_V1</span></div>
<div className="valuation-grid"><form className="valuation-panel" onSubmit={run}><h3>What changes?</h3><div className="valuation-fields">{Object.keys(initial).map(k=><label key={k}>{k}<input className="os-input" type={k==="name"?"text":"number"} step="any" value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><button className="btn-primary" disabled={busy}>{busy?"Simulating…":"Simulate scenario"}</button></form>
<div className="valuation-panel"><span className="home-eyebrow">Propagation</span><h3>Baseline → Scenario</h3>{result?<div className="twin-deltas"><Delta label="Revenue" value={fmt(result.result.delta.revenue)}/><Delta label="EBITDA" value={fmt(result.result.delta.ebitda)}/><Delta label="Burn" value={fmt(result.result.delta.burn)}/><Delta label="Cash" value={fmt(result.result.delta.cash)}/><Delta label="Runway" value={result.result.delta.runwayMonths==null?"—":result.result.delta.runwayMonths+" mo"}/><Delta label="Customers" value={result.result.delta.customers??"—"}/><div className="twin-wide"><span>Monte Carlo P50 EBITDA</span><strong>{fmt(result.result.forecast.terminalEbitda.p50)}</strong><small>{result.result.forecast.probabilityPositiveEbitda}% of paths end EBITDA-positive</small></div><div className="twin-wide"><span>Valuation range</span><strong>{fmt(result.result.valuation.range.low)} — {fmt(result.result.valuation.range.high)}</strong><small>Algorithm champion {result.algorithmVersion}</small></div>{result.result.warnings.map((w:string)=><p key={w} className="twin-warning">{w}</p>)}<small className="twin-wide">{result.result.explanation}</small></div>:<p className="valuation-muted">Create a scenario to propagate funding, growth, customers, CAC and costs through the financial model.</p>}</div></div>
<div className="valuation-panel"><div className="valuation-head"><div><span className="home-eyebrow">Scenario Memory</span><h3>Saved twins</h3></div><small>{history.length} scenario(s)</small></div><div className="scenario-history">{history.slice(0,6).map((s:any)=><article key={s.id}><b>{s.name}</b><small>{new Date(s.createdAt).toLocaleString()} · {s.algorithmVersion??"unversioned"}</small></article>)}</div></div></section>}
function Delta({label,value}:{label:string;value:any}){return <div><span>{label}</span><strong>{value}</strong></div>}
