"use client"; import {FormEvent,useEffect,useState} from "react";
const forecast0={name:"Base forecast",months:"12",revenueGrowth:"5",costGrowth:"3",volatility:"0.08",simulations:"1000",seed:"872"};
const benchmark0={metric:"",value:"",unit:"%",cohort:"",sourceName:"",sourceUrl:""};
const iot0={metric:"",value:"",unit:"",financialMetric:"",conversionRate:"",source:""};
export default function InvestorIntelligenceLab(){const[data,setData]=useState<any>(null),[forecast,setForecast]=useState<any>(forecast0),[benchmark,setBenchmark]=useState<any>(benchmark0),[iot,setIot]=useState<any>(iot0),[simulation,setSimulation]=useState<any>(null);
 const load=async()=>{const r=await fetch("/api/capital/intelligence-lab",{cache:"no-store"});if(r.ok)setData(await r.json())};useEffect(()=>{void load()},[]);
 const send=async(e:FormEvent,kind:string,state:any)=>{e.preventDefault();const r=await fetch("/api/capital/intelligence-lab",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({kind,...state})});const p=await r.json();if(r.ok&&kind==="forecast")setSimulation(p.result);if(r.ok)await load()};
 const money=(v:any)=>v==null?"—":new Intl.NumberFormat("es-CO",{maximumFractionDigits:0}).format(v);
 return <section className="investor-lab"><div className="valuation-head"><div><span className="home-eyebrow">Capital Intelligence</span><h2>Investor Room</h2><p>Forecast, stress-test and defend the venture using traceable evidence.</p></div><span className="badge badge-blue">{data?.investorRoom?.ready??0}/{data?.investorRoom?.total??8} investor answers ready</span></div>
 <div className="investor-questions">{data?.investorRoom?.questions?.map((q:any)=><article key={q.question}><span className={"badge "+(q.status==="READY"?"badge-green":"badge-amber")}>{q.status}</span><b>{q.question}</b><small>{q.answer}</small></article>)}</div>
 <div className="valuation-grid"><form className="valuation-panel" onSubmit={e=>send(e,"forecast",forecast)}><span className="home-eyebrow">Monte Carlo</span><h3>Financial Forecast</h3><Fields state={forecast} set={setForecast}/><button className="btn-primary">Run simulation</button></form>
 <div className="valuation-panel"><span className="home-eyebrow">Sensitivity</span><h3>Simulation distribution</h3>{simulation?<div className="simulation-grid"><Band label="Revenue" x={simulation.terminalRevenue} money={money}/><Band label="EBITDA" x={simulation.terminalEbitda} money={money}/><Band label="Cash" x={simulation.terminalCash} money={money}/><div><span>Positive EBITDA</span><strong>{simulation.probabilityPositiveEbitda}%</strong></div><small>{simulation.simulations} simulations · seed {simulation.seed}. {simulation.disclaimer}</small></div>:<p className="valuation-muted">Run a scenario to see P10, P50 and P90 outcomes.</p>}</div></div>
 <div className="valuation-grid"><form className="valuation-panel" onSubmit={e=>send(e,"benchmark",benchmark)}><span className="home-eyebrow">Big Data Evidence</span><h3>Sourced benchmark</h3><Fields state={benchmark} set={setBenchmark}/><button className="btn-ghost">Add benchmark</button><small>{data?.benchmarks?.length??0} sourced benchmark(s). VELA does not fabricate peer data.</small></form>
 <form className="valuation-panel" onSubmit={e=>send(e,"iot",iot)}><span className="home-eyebrow">IoT Evidence</span><h3>Operational signal</h3><Fields state={iot} set={setIot}/><button className="btn-ghost">Record IoT signal</button><small>{data?.iot?.length??0} operational signal(s) available for financial interpretation.</small></form></div></section>}
function Fields({state,set}:{state:any;set:(x:any)=>void}){return <div className="valuation-fields">{Object.keys(state).map(k=><label key={k}>{k}<input className="os-input" type={["name","metric","unit","cohort","sourceName","sourceUrl","financialMetric","source"].includes(k)?"text":"number"} step="any" value={state[k]} onChange={e=>set({...state,[k]:e.target.value})}/></label>)}</div>}
function Band({label,x,money}:{label:string;x:any;money:(v:any)=>string}){return <div><span>{label}</span><strong>P50 {money(x.p50)}</strong><small>P10 {money(x.p10)} · P90 {money(x.p90)}</small></div>}
