"use client";

import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { FormEvent, Suspense, useState } from "react";
import BrandLogo from "@/components/brand-logo";

function SignupForm() {
  const router = useRouter(); const searchParams = useSearchParams(); const nextPath = searchParams.get("next") || "";
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(null); try { const response = await fetch("/api/auth/register", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name, email, password }) }); const data = await response.json().catch(() => ({})) as { error?: string; verificationUrl?: string }; if (!response.ok) throw new Error(data.error || "Unable to create account."); if (data.verificationUrl) { router.replace(`/verify-email?url=${encodeURIComponent(data.verificationUrl)}`); } else { router.replace("/login?registered=success"); } } catch (err) { setError(err instanceof Error ? err.message : "Unable to create account."); setLoading(false); } }
  return <div className="access-form-panel"><span className="access-eyebrow">BEGIN WITH VELA</span><h1>Start building.</h1><p className="access-lede">Create your account and give your next idea a system.</p><form onSubmit={submit} className="access-form"><label>Name<input autoComplete="name" value={name} onChange={(e) => setName(e.target.value)} required minLength={2} /></label><label>Email<input type="email" autoComplete="email" value={email} onChange={(e) => setEmail(e.target.value)} required /></label><label>Password<input type="password" autoComplete="new-password" value={password} onChange={(e) => setPassword(e.target.value)} required minLength={6} /></label><button className="access-submit" type="submit" disabled={loading}>{loading ? "Creating account..." : "Create account"}<span>→</span></button>{error && <p className="access-error" role="alert">{error}</p>}</form><p className="access-switch">Already building? <Link href={`/login${nextPath ? `?next=${encodeURIComponent(nextPath)}` : ""}`}>Sign in</Link></p></div>;
}

export default function SignupPage() { return <main className="access-shell"><section className="access-visual"><Link href="/launch" className="access-brand"><BrandLogo variant="wordmark" priority /><span>VENTURE OPERATING SYSTEM</span></Link><div className="access-visual-copy"><span>FROM IDEAS TO EXTRAORDINARY COMPANIES</span><h2>Build the next<br />possible.</h2><p>Join a system designed for direction, execution, evidence and growth.</p></div></section><section className="access-panel"><div className="access-panel-top"><span>ALREADY BUILDING?</span><Link href="/login">Sign in →</Link></div><Suspense fallback={<div className="access-form-panel">Loading access...</div>}><SignupForm /></Suspense><div className="access-footer-mark">VELA <span>VENTURE OPERATING SYSTEM</span></div></section></main>; }
