import {NextRequest,NextResponse} from "next/server";import {requireAuth} from "@/lib/api-auth";import {prisma} from "@/lib/prisma";import {optimizeCapitalScenario} from "@/lib/capital-scenario-optimizer";import {getAlgorithmParameters} from "@/lib/algorithm-learning";import {getGovernedParameters} from "@/lib/algorithm-governance";import {dispatchDomainEvent} from "@/lib/domain-events";
export const dynamic="force-dynamic";
export async function POST(req:NextRequest){const a=await requireAuth(req);if(!a.ok)return a.response;const v=await prisma.venture.findUnique({where:{userId:a.session.sub}});if(!v)return NextResponse.json({error:"Create a venture first."},{status:409});const base=await prisma.financialSnapshot.findFirst({where:{ventureId:v.id},orderBy:{period:"desc"}});if(!base)return NextResponse.json({error:"Financial snapshot required."},{status:409});const b=await req.json().catch(()=>({}));const n=(x:any,d=0)=>x===""||x==null?d:Number(x);
const assumptions={months:n(b.months,12),revenueGrowth:n(b.revenueGrowth,5),costGrowth:n(b.costGrowth,3),volatility:n(b.volatility,.08),simulations:n(b.simulations,300),seed:n(b.seed,872),revenueMultiple:b.revenueMultiple===""?null:n(b.revenueMultiple),ebitdaMultiple:b.ebitdaMultiple===""?null:n(b.ebitdaMultiple),discountRate:b.discountRate===""?null:n(b.discountRate),terminalGrowth:b.terminalGrowth===""?null:n(b.terminalGrowth),projectedGrowth:b.projectedGrowth===""?null:n(b.projectedGrowth)};
const bounds={capitalRaise:[n(b.minCapitalRaise,0),n(b.maxCapitalRaise,1000000000)] as [number,number],equityOffered:[n(b.minEquity,5),n(b.maxEquity,15)] as [number,number],revenueChangePct:[n(b.minRevenueChange,0),n(b.maxRevenueChange,30)] as [number,number],customerChangePct:[n(b.minCustomerChange,0),n(b.maxCustomerChange,30)] as [number,number],cacChangePct:[n(b.minCacChange,-25),n(b.maxCacChange,10)] as [number,number],monthlyHiringCost:[n(b.minHiringCost,0),n(b.maxHiringCost,50000000)] as [number,number],additionalMonthlyCosts:[n(b.minAdditionalCosts,0),n(b.maxAdditionalCosts,20000000)] as [number,number]};
const constraints={maxDilution:n(b.maxDilution,15),minRunwayMonths:n(b.minRunwayMonths,18),minPositiveEbitdaProbability:n(b.minPositiveEbitdaProbability,60),maxMonthlyBurn:n(b.maxMonthlyBurn,Number.MAX_SAFE_INTEGER)};
const result=optimizeCapitalScenario(base,assumptions,bounds,constraints,{iterations:n(b.iterations,18),population:n(b.population,24),seed:n(b.seed,872)});
const adaptive=await getAlgorithmParameters(a.session.sub);const governed=await getGovernedParameters(a.session.sub,adaptive);
if(result.best){const row=await prisma.capitalScenario.create({data:{ventureId:v.id,name:String(b.name||"Optimized scenario"),baseline:base as unknown as object,changes:result.best.changes as unknown as object,assumptions:assumptions as unknown as object,result:{...result.best.result,optimization:{score:result.best.score,feasible:result.best.feasible,reasons:result.best.reasons,trace:result.trace}} as unknown as object,algorithmVersion:governed.version}});await dispatchDomainEvent("capital_scenario_optimized",{scenarioId:row.id,ventureId:v.id,ownerId:a.session.sub,score:result.best.score,feasible:result.best.feasible});}
return NextResponse.json({...result,algorithmVersion:governed.version});}