import{NextRequest,NextResponse}from"next/server";import{requireAuth}from"@/lib/api-auth";import{prisma}from"@/lib/prisma";import{analyzeTeamCapacity}from"@/lib/team-capacity";import{synthesizeResourceIntelligence}from"@/lib/resource-intelligence";import{synthesizeCapitalLearning}from"@/lib/capital-learning";import{synthesizeCrossModuleSignals}from"@/lib/cross-module-signals";export const dynamic="force-dynamic";
export async function GET(req:NextRequest){const a=await requireAuth(req);if(!a.ok)return a.response;const v=await prisma.venture.findUnique({where:{userId:a.session.sub},select:{id:true}});if(!v)return NextResponse.json({status:"NO_VENTURE",signals:[]});
 const [deployments,members,assignments,resources,objectives,sprints,validationSignals]=await Promise.all([
 prisma.capitalDeployment.findMany({where:{ventureId:v.id},orderBy:{createdAt:"asc"}}),
 prisma.ventureMember.findMany({where:{ventureId:v.id,status:"active"},include:{user:{select:{name:true}}}}),
 prisma.workAssignment.findMany({where:{ventureId:v.id}}),
 prisma.spaceResource.findMany({where:{ventureId:v.id},include:{allocations:{where:{status:"active"}}}}),
 prisma.objective.findMany({where:{ownerId:a.session.sub,status:{not:"completed"}},select:{id:true,status:true}}),
 prisma.sprint.findMany({where:{ownerId:a.session.sub},orderBy:{weekStart:"desc"},take:3,include:{items:true}}),
 prisma.signal.findMany({where:{ownerId:a.session.sub},orderBy:{createdAt:"desc"},take:100,select:{type:true,createdAt:true}})
 ]);
 const learning=synthesizeCapitalLearning(deployments);const learned=deployments.filter(x=>x.closedAt&&x.learning);const mid=Math.max(1,Math.floor(learned.length/2));const avg=(xs:typeof learned)=>xs.length?xs.reduce((s,x)=>s+(x.roi??0),0)/xs.length:null;const previous=avg(learned.slice(0,mid)),recent=avg(learned.slice(mid));
 const team=analyzeTeamCapacity(members.map(m=>({id:m.id,name:m.user.name,role:m.role,status:m.status})),assignments);const ri=synthesizeResourceIntelligence(resources.map(r=>({id:r.id,title:r.title,resourceType:r.resourceType,status:r.status,criticality:r.criticality,monthlyCost:r.monthlyCost,ownerMemberId:r.ownerMemberId,usageStatus:r.usageStatus,allocations:r.allocations.length})));
 const current=sprints.find(s=>s.status==="active")??sprints[0]??null;const openItems=current?.items.filter(i=>!i.done).length??0,completion=current?.items.length?Math.round(current.items.filter(i=>i.done).length/current.items.length*100):null;const now=Date.now(),recentSignals=validationSignals.filter(s=>now-s.createdAt.getTime()<=14*86400000).length;
 const result=synthesizeCrossModuleSignals({capital:{samples:learning.samples,portfolioEfficiency:learning.portfolioEfficiency,recentEfficiency:recent,previousEfficiency:previous,reallocation:learning.reallocation,planned:deployments.reduce((s,x)=>s+x.plannedAmount,0),spent:deployments.reduce((s,x)=>s+x.spentAmount,0),openDeployments:deployments.filter(x=>x.status!=="closed").map(x=>({title:x.title,planned:x.plannedAmount,spent:x.spentAmount,status:x.status,milestone:x.milestone}))},team:{members:members.length,totalLoad:team.totalLoad,overloaded:team.overloaded,concentration:team.concentration},resources:{monthlyCost:ri.health.monthlyCost,unusedPaid:ri.health.unusedPaid,criticalUnavailable:ri.health.criticalUnavailable,criticalUnallocated:resources.filter(r=>r.criticality==="critical"&&r.allocations.length===0).length},build:{active:objectives.length,blocked:objectives.filter(x=>x.status==="blocked").length,atRisk:objectives.filter(x=>x.status==="at_risk").length},validation:{signals:validationSignals.length,interviews:validationSignals.filter(x=>x.type==="interview").length,recentSignals},sprint:{active:current?.status==="active",completion,openItems}});
 return NextResponse.json({...result,context:{capitalLearning:learning,team:{totalLoad:team.totalLoad,overloaded:team.overloaded,concentration:team.concentration},resources:ri.health}});}
